- hosts: demo
  gather_facts: False
  become: true
  connection: ssh
  vars_files:
    - vars/default.yml
  roles:
    - amz
    - apache
    - mariadb
    - py
    - php
    - mariadb
    - wordpress

