- hosts: web
  gather_facts: False
  become: true
  connection: ssh
  vars_files:
    - vars/default.yml
  tasks:
    - name: Upgrade amazonec2
      action: yum name=amazon-linux-extras state=present
    - name: Enable amazon-extras
      shell: "amazon-linux-extras enable {{item}}"
      with_items: "{{php7.4}}"

  roles:
    - apache
   
    - mysql
    - php
    - wordpress
    
