- name: Install MySQL Packages
  apt: name={{ item }} update_cache=yes state= latest
  loop: "{{ sql_packages }}"
   
- name: Start mysqld service
  service: name=mariadb state=started enabled=yes
  
- name: Set MySQL root Password
  mysql_user:
        name: 'root'
        host_all: yes
        password: '{{ mysql_root_password }}'
        state: present
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"

- name: Creates database for WordPress
  mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
 
- name: Create MySQL user for WordPress
  mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
