#- name: Install PHP Extensions
#  apt: name= '{{item}}' update_cache=yes state=present
#  with_items: [ 'php', 'php-mysql', 'php-gd', 'php-cli', 'php-common' ]
          

- name: Install PHP Extensions
  command: " apt install php php-mysql php-gd php-cli php-common -y"
  become: yes






- name: Start httpd service
  systemd: name=apache2 state=started
