
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/www.site.com"
        remote_src: yes
        creates: "/var/www/www.site.com/wordpress"

    - name: Set ownership
      file:
        path: "/var/www/www.site.com"
        state: directory
        recurse: yes
        owner: apache
        group: apache
 
    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/www.site.com/wordpress/ -type d -exec chmod 750 {} \\;"
 
    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/www.site.com/wordpress/ -type f -exec chmod 640 {} \\;"
 
    - name: Copy sample config file
      command: "mv /var/www/www.site.com/wordpress/wp-config-sample.php /var/www/www.site.com/wordpress/wp-config.php creates=/var/www/www.site.com/wordpress/wp-config.php"
      become: yes
 
    - name: Update WordPress config file
      lineinfile:
        path: "/var/www/www.site.com/wordpress/wp-config.php"
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      with_items:
        - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{mysql_db}}' );"}
        - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{mysql_user}}' );"}
        - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{mysql_password}}' );"}
     
    - name: Restart httpd service
      systemd: name=httpd state=restarted
      become: yes
