- name: Install NGINX
  apt: name=nginx state=latest

- name: Rename default conf file2
  file:
    src: /etc/nginx/sites-available/default
    state: absent

- name: Configure NGINX for wordpress
  template:
    src: "files/default"
    dest: "/etc/nginx/sites-available"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Rename default conf file
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/

- name: Restart NGINX
  systemd: name=nginx state=restarted enabled=yes
  
